name: WakaTime Readme Stats

on:
  schedule:
    - cron: "0 0 * * *"   # every day at 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_OS: "false"
          SHOW_PROJECTS: "false"
          SHOW_TIMEZONE: "false"
          SHOW_EDITORS: "false"
          SHOW_LOC_CHART: "false"
